services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: gift_card_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_root_password_here
      MYSQL_DATABASE: gift_card_system
      MYSQL_USER: giftcard_user
      MYSQL_PASSWORD: your_strong_password_here
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - gift_card_network
    command: --default-authentication-plugin=mysql_native_password

  # Node.js应用
  app:
    build: .
    container_name: gift_card_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_USER: giftcard_user
      DB_PASSWORD: your_strong_password_here
      DB_NAME: gift_card_system
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      PORT: 3000
    depends_on:
      - mysql
    networks:
      - gift_card_network
    volumes:
      - ./locales:/app/locales:ro
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis (可选，用于会话存储和缓存)
  redis:
    image: redis:7-alpine
    container_name: gift_card_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - gift_card_network
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  gift_card_network:
    driver: bridge
