services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: gift_card_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: GiftCard_Root_2024!
      MYSQL_DATABASE: gift_card_system
      MYSQL_USER: giftcard_user
      MYSQL_PASSWORD: GiftCard_User_2024!
    # 添加端口映射，使本地应用能连接到Docker中的MySQL
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - gift_card_network
    command: --default-authentication-plugin=mysql_native_password

  # Node.js应用
  app:
    build: .
    container_name: gift_card_app
    restart: unless-stopped
    # 移除直接端口映射，由 Nginx 代理
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_USER: giftcard_user
      DB_PASSWORD: GiftCard_User_2024!
      DB_NAME: gift_card_system
      JWT_SECRET: GiftCard_JWT_Secret_Key_2024_Super_Complex_String
      PORT: 3000
    depends_on:
      - mysql
    networks:
      - gift_card_network
    volumes:
      - ./locales:/app/locales:ro
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis (可选，用于会话存储和缓存)
  redis:
    image: redis:7-alpine
    container_name: gift_card_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - gift_card_network
    volumes:
      - redis_data:/data
      
  # Nginx 反向代理
  nginx:
    image: nginx:1.25-alpine
    container_name: gift_card_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "3000:80"  # 同时映射到 3000 端口，保持兼容性
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/grom/wwwroot/giftcard/public:/public:ro
      - nginx_cache:/var/cache/nginx  # Nginx 缓存
      - nginx_logs:/var/log/nginx  # Nginx 日志
    depends_on:
      - app
    networks:
      - gift_card_network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  nginx_cache:
    driver: local
  nginx_logs:
    driver: local

networks:
  gift_card_network:
    driver: bridge
